/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#767575",
        "inverse-on-surface": "#565555",
        "error-dim": "#d7383b",
        "on-secondary": "#001e4a",
        "tertiary": "#67ccff",
        "on-background": "#ffffff",
        "inverse-primary": "#006b60",
        "surface": "#0e0e0e",
        "on-secondary-fixed": "#003271",
        "primary": "#5bf4de",
        "primary-fixed": "#5bf4de",
        "primary-dim": "#48e5d0",
        "surface-container": "#1a1a1a",
        "outline-variant": "#484847",
        "surface-container-high": "#20201f",
        "surface-dim": "#0e0e0e",
        "primary-container": "#11c9b4",
        "on-primary-fixed": "#00443c",
        "on-tertiary": "#00415a",
        "secondary-container": "#005ac2",
        "surface-variant": "#262626",
        "surface-tint": "#5bf4de",
        "tertiary-fixed": "#1dc0fe",
        "on-error-container": "#ffa8a3",
        "surface-bright": "#2c2c2c",
        "primary-fixed-dim": "#48e5d0",
        "secondary-dim": "#699cff",
        "on-secondary-container": "#f7f7ff",
        "surface-container-lowest": "#000000",
        "on-error": "#490006",
        "on-tertiary-container": "#00374c",
        "on-surface-variant": "#adaaaa",
        "tertiary-dim": "#00b2ed",
        "on-tertiary-fixed": "#001e2b",
        "on-secondary-fixed-variant": "#004da8",
        "tertiary-fixed-dim": "#00b2ed",
        "secondary-fixed-dim": "#a9c4ff",
        "background": "#0e0e0e",
        "on-primary-container": "#003a33",
        "on-tertiary-fixed-variant": "#004058",
        "on-surface": "#ffffff",
        "surface-container-highest": "#262626",
        "secondary-fixed": "#bfd1ff",
        "tertiary-container": "#1dc0fe",
        "on-primary-fixed-variant": "#006358",
        "error-container": "#9f0519",
        "secondary": "#699cff",
        "surface-container-low": "#131313",
        "inverse-surface": "#fcf9f8",
        "error": "#ff716c",
        "on-primary": "#00594f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
